### ISSUE TITLE
Fail when build an app that no have sqlc.yaml file

### ISSUE THREAD

**Issue by guipassos** [renanbastos93/boneless#1]
When I try to build an app that no have sqlc.yaml file, I receive a panic on the build, with message:

![image](https://github.com/renanbastos93/boneless/assets/9012209/7f00c857-ea15-4d4b-b0ed-855d211eda05)

This issue also occurs when build all applications and it breaking the next builds.

**Comment by renanbastos93** [comment]
Hey, @guipassos thanks for your report. 

I opened PR #5 to fix that. Might you do a review and test that?

regards
